export const lineChartOptions = {
  plugins: {
    datalabels: false,
  },
  tooltips: {
    enabled: false,
  },
  scales: {
    xAxes: [
      {
        gridLines: {
          display: true,
          color: '#373f5b',
          offsetGridLines: false,

          lineWidth: 0.7,
          drawBorder: false,
          drawTicks: false,
        },
        barPercentage: 0.05,

        ticks: {
          fontColor: '#fff',
          fontSize: 12,
          stepSize: 1,
          padding: 15,
          beginAtZero: false,
          callback: function(value, index, values) {
            return value
          },
        },
      },
    ],
    yAxes: [
      {
        gridLines: {
          display: true,
          color: '#373f5b',
          lineWidth: 0.7,
          drawBorder: true,
          drawTicks: false,
          zeroLineColor: 'transparent',
        },
        ticks: {
          fontColor: '#fff',
          fontSize: 12,
          stepSize: 25,
          beginAtZero: true,
          padding: -35,

          callback: function(value, index, values) {
            if (value === 0 || value === 100) {
              return value
            } else {
              return ''
            }
          },
        },
      },
    ],
  },
}
export const lineChartData_DatasetOptions = [
  {
    fill: false,
    type: 'line',
    label: 'Dataset 1',

    lineTension: 0.1,
    borderColor: '#8562f3',
    borderCapStyle: 'butt',
    borderDash: [],
    borderWidth: 5,
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointRadius: 5,
    pointBackgroundColor: '#8562f3',
    pointBorderColor: '#fff',
    pointBorderWidth: 1,
    pointHoverRadius: 5,
    pointHoverBackgroundColor: 'rgba(75,192,192,1)',
    pointHoverBorderColor: 'rgba(220,220,220,1)',
    pointHoverBorderWidth: 2,
    pointHitRadius: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    shadowBlur: 5,
    shadowColor: '#8562f3',
  },
  {
    fill: false,
    type: 'line',
    label: 'Dataset 3',

    lineTension: 0.1,
    borderWidth: 5,
    borderColor: '#2fd7c4',
    borderCapStyle: 'butt',
    borderDash: [],
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointRadius: 5,
    pointBackgroundColor: '#2fd7c4',
    pointBorderColor: '#fff',
    pointBorderWidth: 1,
    pointHoverRadius: 5,
    pointHoverBackgroundColor: 'rgba(75,192,192,1)',
    pointHoverBorderColor: 'rgba(220,220,220,1)',
    pointHoverBorderWidth: 2,
    pointHitRadius: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    shadowBlur: 5,
    shadowColor: '#2fd7c4',
  },
  {
    fill: false,
    type: 'line',
    lineTension: 0.1,
    label: 'Dataset 4',

    borderColor: '#acb0be',
    borderCapStyle: 'butt',
    borderDash: [],
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointRadius: 5,
    pointBackgroundColor: '#acb0be',
    pointBorderColor: '#fff',
    pointBorderWidth: 1,
    borderWidth: 5,
    pointHoverRadius: 5,
    pointHoverBackgroundColor: 'rgba(75,192,192,1)',
    pointHoverBorderColor: 'rgba(220,220,220,1)',
    pointHoverBorderWidth: 2,
    pointHitRadius: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    shadowBlur: 5,
    shadowColor: '#acb0be',
  },
  {
    fill: false,
    type: 'line',
    lineTension: 0.1,
    label: 'Dataset 5',

    borderColor: '#5292e5',
    borderCapStyle: 'butt',
    borderDash: [],
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointRadius: 5,
    pointBackgroundColor: '#5292e5',
    pointBorderColor: '#fff',
    pointBorderWidth: 1,
    pointHoverRadius: 5,
    borderWidth: 5,
    pointHoverBackgroundColor: 'rgba(75,192,192,1)',
    pointHoverBorderColor: 'rgba(220,220,220,1)',
    pointHoverBorderWidth: 2,
    pointHitRadius: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    shadowBlur: 5,
    shadowColor: '#5292e5',
  },
  {
    fill: false,
    label: 'Dataset 6',

    type: 'line',
    lineTension: 0.1,
    borderColor: '#545b79',
    borderCapStyle: 'butt',
    borderDash: [],
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointRadius: 5,
    pointBackgroundColor: '#545b79',
    pointBorderColor: '#fff',
    pointBorderWidth: 1,
    pointHoverRadius: 5,
    borderWidth: 5,
    pointHoverBackgroundColor: 'rgba(75,192,192,1)',
    pointHoverBorderColor: 'rgba(220,220,220,1)',
    pointHoverBorderWidth: 2,
    pointHitRadius: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    shadowBlur: 5,
    shadowColor: '#545b79',
  },
  {
    type: 'bar',
    label: 'Dataset 2',
    backgroundColor: '#fff',
    borderColor: 'white',
    borderWidth: 2,
  },
]
