export default {
  labels: [
    "Dec 1st",
    "Dec 2nd",
    "Dec 3rd",
    "Dec 4th",
    "Dec 5th",
    "Dec 6th",
    "Dec 7th"
  ],
  datasets: [{
      fill: false,
      lineTension: 0.1,
      backgroundColor: "rgba(75,192,192,0.4)",
      borderColor: "#5292E5",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointRadius: 5,
      pointBackgroundColor: "#5292E5",
      pointBorderColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "rgba(75,192,192,1)",
      pointHoverBorderColor: "rgba(220,220,220,1)",
      pointHoverBorderWidth: 2,
      pointHitRadius: 10,
      shadowOffsetX: 1,
			shadowOffsetY: 1,
			shadowBlur: 5,
			shadowColor: "#5292E5",
      data: [0.5, 0.4, 0.7, 0.9, 0.1, 0.3, 0.7]
    },
    {
      fill: false,
      lineTension: 0.1,
      backgroundColor: "rgba(75,192,192,0.4)",
      borderColor: "#8562F3",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointRadius: 5,
      pointBackgroundColor: "#8562F3",
      pointBorderColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "rgba(75,192,192,1)",
      pointHoverBorderColor: "rgba(220,220,220,1)",
      pointHoverBorderWidth: 2,
      pointHitRadius: 10,
      shadowOffsetX: 1,
			shadowOffsetY: 1,
			shadowBlur: 5,
			shadowColor: "#8562F3",
      data: [1.2, 1.8, 1.4, 1.1, 2, 1.4, 1.8]
    },
    {
      fill: false,
      lineTension: 0.1,
      backgroundColor: "rgba(75,192,192,0.4)",
      borderColor: "#51acc0",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointRadius: 5,
      pointBackgroundColor: "#51acc0",
      pointBorderColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "rgba(75,192,192,1)",
      pointHoverBorderColor: "rgba(220,220,220,1)",
      pointHoverBorderWidth: 2,
      pointHitRadius: 10,
      shadowOffsetX: 1,
			shadowOffsetY: 1,
			shadowBlur: 5,
			shadowColor: "#51acc0",
      data: [3.1, 2.5, 2.8, 2.6, 3.2, 2.9, 3.1]
    }
  ]
};