export const percentageGraphOptions = [
  {
    fill: true,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    lineTension: 0,
    borderCapStyle: 'butt',
    borderDash: [],
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointRadius: 0,
    pointBackgroundColor: 'transparent',
    pointBorderColor: 'transparent',
    pointBorderWidth: 0,
    pointHoverRadius: 0,
    pointHoverBackgroundColor: 'transparent',
    pointHoverBorderColor: 'transparent',
    pointHoverBorderWidth: 0,
    pointHitRadius: 0,
  },
]
